### ISSUE TITLE
Service calls broken for OS X

### ISSUE THREAD

**Issue by beverlylytle** [gramaziokohler/roslibpy#43]
When making a service call without a callback, the blocking mechanism for the call seems to be interfering with the service request.

## Expected Result
When running the code below with appropriate docker containers are running, I expect a string of the form 
"Service response: {'topics': ['/client_count', '/rosout', '/rosout_agg', '/connected_clients'], 'types': ['std_msgs/Int32', 'rosgraph_msgs/Log', 'rosgraph_msgs/Log', 'rosbridge_msgs/ConnectedClients']}" to be printed.  

## Actual Result
Running the code below results in an exception "No service response received" which can be avoided by setting various timeout limits in the source code unacceptably high.

## Reproduction Steps
```python
import roslibpy

client = roslibpy.Ros(host='localhost', port=9090)
client.run()

service = roslibpy.Service(client, '/rosapi/topics', 'rosapi/Topics')
request = roslibpy.ServiceRequest()

print('Calling service...')
result = service.call(request, callback=None, errback=None, timeout=3)
print('Service response: {}'.format(result))

client.terminate()

```
with docker-compse.yml

```yml
version: '2'
services:
  ros-master:
    image: gramaziokohler/ros-base:19.04
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-ur-planner:19.04
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
```

## System Information
Run on OS 10.15.1 with roslibpy version 0.7.0
